### ISSUE TITLE
Update scala-graph library to eliminate scalacheck from runtime

### ISSUE THREAD

**Issue by alkersan** [salesforce/TransmogrifAI#105]
**Problem**
`features` module at the moment is using `scala-graph 1.11.2` library, which has transitive dependency on `scalacheck` testing library, but not in the `test` or `optional` scope. Probably it was a minor mistake in the early days of `scala-graph` development, which was [fixed](https://github.com/scala-graph/scala-graph/commit/9604e37389d347e5ea3185ff7922b1d40fda8dec) quite long ago. From the end-user perspective this might be suspicious at minimum, e.g. my first question during dependency troubleshooting and spark job assembly building was: _what this test dependency is doing in the runtime?_

![image](https://user-images.githubusercontent.com/527045/44857226-fff2fb80-ac77-11e8-9819-37b88ae3df5a.png)

**Solution**
The aforementioned fix is available since `1.11.4`, while the last version in the `1.11` branch is `1.11.5`.
Solution might be as simple as bumping the `scalaGraphVersion`, thus reducing dependency tree a bit and simplifying the assembly building for the users.

**Comment by tovbinm** [comment]
@alkersan thank you for pointing this out. I will make a PR with the version bump.
