### ISSUE TITLE
Can somebody help me understand the outputs of the scripts?

### ISSUE THREAD

**Issue by Tian-Su** [salesforce/TransmogrifAI#109]
**Problem**
The meaning of the output of the `./gradlew -q sparkSubmit -Dmain=com.salesforce.hw.OpTitanicSimple -Dargs="`pwd`/src/main/resources/TitanicDataset/TitanicPassengersTrainData.csv"` is not clear

**Solution**
Could somebody help me through it chunk by chunk?

**Alternatives**
Build in more interpretable result presentation in the script.

**Additional context**
Can't paste the result here.... way too long....

**Comment by tovbinm** [comment]
Instead of printing out model.summary, try model.summaryPretty. It will print you a shorter version of the results.

**Comment by tovbinm** [comment]
@Tian-Su which part in particular confuses you?
