### ISSUE TITLE
Missing com.salesforce.hw.iris.Iris class in iris example

### ISSUE THREAD

**Issue by fyuan1316** [salesforce/TransmogrifAI#113]
**Describe the bug**
hi , all.
I started with the example of iris, but i can't find "com.salesforce.hw.iris.Iris".

**To Reproduce**
Minimal set of steps or code snippet to reproduce the behavior

**Expected behavior**

**Logs or screenshots**
If applicable, add logs or screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/42265657/45072880-6613ce80-b10f-11e8-966b-02a5089a8e1c.png)
![image](https://user-images.githubusercontent.com/42265657/45072899-77f57180-b10f-11e8-8b80-e1277c3087c0.png)

**Additional context**

**Comment by tovbinm** [comment]
`com.salesforce.hw.iris.Iris` is class that is autogenerated at compile time using the avro plugin. You should be able to see it Intellij as well as in `helloworld/build/generated-main-avro-java/com/salesforce/hw/iris/Iris.java` once you run the build: `cd helloworld && ./gradlew compileTestScala`

**Comment by fyuan1316** [comment]
Thank you for your quick reply. 
Based on your guidance, I just reviewed the first example (the Titanic) and found the initial steps, as you wrote.
thanks a lot. :)
