### ISSUE TITLE
No feature type tag mapping for Spark type IntegerType

### ISSUE THREAD

**Issue by liuzhenhai93** [salesforce/TransmogrifAI#115]
**Describe the bug**
spark sql type integer is not mapped to featuretype
in the source code,type is mapped as bellow.
def featureTypeTagOf(sparkType: DataType, isNullable: Boolean): WeakTypeTag[_ <: FeatureType] = sparkType match {
    case DoubleType if !isNullable => weakTypeTag[types.RealNN]
    case DoubleType => weakTypeTag[types.Real]
 // **add this line  and tweak method fromSparkFn in FeatureTypeSparkConverter.scala can fix the bug**
  // case IntegerType => weakTypeTag[types.Integral]

    case LongType => weakTypeTag[types.Integral]
    case ArrayType(StringType, _) => weakTypeTag[types.TextList]
    case StringType => weakTypeTag[types.Text]
    case BooleanType => weakTypeTag[types.Binary]
    ......
    case _ => throw new IllegalArgumentException(s"No feature type tag mapping for Spark type $sparkType")
  }
 **and change  line 153 ( in method fromSparkFn)  in FeatureTypeSparkConverter.scala to:** 
 case wt if wt <:< weakTypeOf[t.Integral] => (value: Any) => {
        var result: Any = FeatureTypeDefaults.Integral.value
        if (value == null) {result = FeatureTypeDefaults.Integral.value}
        else if (value.isInstanceOf[Integer]) {result = Some(value.asInstanceOf[Int].toLong)}
        else {result = Some(value.asInstanceOf[Long])}
        result
        }

**To Reproduce**
package com.jd.spark
import com.salesforce.op._
import com.salesforce.op.readers._
import com.salesforce.op.features._
import com.salesforce.op.features.types._
import com.salesforce.op.stages.impl.classification._
import org.apache.spark.SparkConf
import org.apache.spark.sql.SparkSession
import org.apache.spark.sql.functions.udf
case class Passenger(
  id: Int,
  survived: Int,
  pClass: Option[Int],
  name: Option[String],
  sex: Option[String],
  age: Option[Double],
  sibSp: Option[Int],
  parCh: Option[Int],
  ticket: Option[String],
  fare: Option[Double],
  cabin: Option[String],
  embarked: Option[String])
object TestSalesForce {
  def main(args: Array[String]) = {
    implicit val spark = SparkSession.builder.config(new SparkConf().setMaster("local")).enableHiveSupport()
      .getOrCreate()
    import spark.implicits._

    // Read Titanic data as a DataFrame
    val passengersData = DataReaders.Simple.csvCase[Passenger](path = Option("D:\\JDdev\\TransmogrifAI\\test-data\\PassengerDataAll.csv")).readDataset().toDF()
     // .selectExpr("id", "cast (survived as double)survived", "pClass", "name", "sex", "age", "sibSp", "parCh", "ticket", "fare", "cabin", "embarked")
    // Extract response and predictor Features
    val (survived, predictors) = FeatureBuilder.fromDataFrame[RealNN](passengersData, response = "survived")

    // Automated feature engineering
    
    val featureVector = predictors.transmogrify()

    // Automated feature validation and selection
    val checkedFeatures = survived.sanityCheck(featureVector, removeBadFeatures = true)

    // Automated model selection
    val pred = BinaryClassificationModelSelector().setInput(survived, checkedFeatures).getOutput()

    // Setting up a TransmogrifAI workflow and training the model
    val model = new OpWorkflow().setInputDataset(passengersData).setResultFeatures(checkedFeatures).train()
    val num=1
    val lnum=num.asInstanceOf[Long]
    //val model = new OpWorkflow().setInputDataset(passengersData).setResultFeatures(Array(pred._1,pred._2,pred._3):_*).train()
    var score = model.score().cache()
    val testf=score.schema("label").dataType
    val field1 = score.schema.fields(0).name
    val field2 = score.schema.fields(1).name
    var test = score.withColumnRenamed(s"$field2", "vec")
    //test=test.withColumn("label", $"0.0")
    val code = (arg: String) => {
      0.0
    }
    val addCol = udf(code)
    test = test.withColumn("label", addCol(test(s"$field1")))
    test=test.select("label", "vec")
    test.printSchema()
    test.write.format("orc").save("test/orc")
    test.write.format("json").save("test/json")
    test.write.format("libsvm").save("test/libsvm")

    //println("Model summary:\n" + model.summaryPretty())
  }
}

**Expected behavior**
spark sql Integer type will map to feature type integal

**Logs or screenshots**

Exception in thread "main" java.lang.IllegalArgumentException: No feature type tag mapping for Spark type IntegerType
	at com.salesforce.op.features.FeatureSparkTypes$.featureTypeTagOf(FeatureSparkTypes.scala:216)
	at com.salesforce.op.features.FeatureBuilder$$anonfun$1.apply(FeatureBuilder.scala:199)
	at com.salesforce.op.features.FeatureBuilder$$anonfun$1.apply(FeatureBuilder.scala:196)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
	at com.salesforce.op.features.FeatureBuilder$.fromDataFrame(FeatureBuilder.scala:196)
	at com.jd.spark.TestSalesForce$.main(TestSalesForce.scala:33)
	at com.jd.spark.TestSalesForce.main(TestSalesForce.scala)

**Additional context**
map from int to feature type

**Comment by tovbinm** [comment]
Good point. I think we can easily add it. For now you can use `Long` for `Integral` feature type.

**Comment by albertodema** [comment]
I also found this: "No feature type tag mapping for Spark type TimestampType", when a field is like '2018-09=09'
