### ISSUE TITLE
View model's predictions and probabilities of each prediction class

### ISSUE THREAD

**Issue by albertodema** [salesforce/TransmogrifAI#121]
**Problem**
Hi currently using the Model score functionality I can only see predictions but not the associated probability

**Solution**
I would like to view predictions and probabilities of each prediction class.
One example of the desired functionality is described here:
https://docs.databricks.com/spark/latest/mllib/binary-classification-mllib-pipelines.html

Thanks.
Alberto.

**Comment by tovbinm** [comment]
are you running it on `0.3.4` release? if so, hen simply add raw prediction and probability into your result features:
```scala
val (pred, rawPred, prob) = modelSelector.getOutput()
val model = new OpWorkFlow()setReader(reader).setResultFeatures(pred, rawPred, prob).train()
val scores = model.score()
```

**Comment by tovbinm** [comment]
In the upcoming `0.4.0` release the result type of the model selector will be the combined type that contains all three values - http://docs.transmogrif.ai/en/master/developer-guide/#modelselector

**Comment by albertodema** [comment]
Many thanks for your answer! 
What about RegressionModelSelector? 
Probabilities are missing because the underlying models are not producing it?

**Comment by tovbinm** [comment]
Correct.
