### ISSUE TITLE
Quick Start Examples (Titanic) Does not Build with 0.3.4 branch

### ISSUE THREAD

**Issue by zzdgit** [salesforce/TransmogrifAI#126]
**Describe the bug**
When I execute Titanic Binary Classification example
./gradlew compileTestScala installDist  it can not download need jar package，

![image](https://user-images.githubusercontent.com/27891681/45412227-bc9d8180-b6a8-11e8-904b-ec88b04bbc03.png)

![image](https://user-images.githubusercontent.com/27891681/45412301-dfc83100-b6a8-11e8-805e-bfc108ccf6a9.png)

I hope you can provide a stable jar package address。。。

thanks

**Comment by tovbinm** [comment]
From the screenshot above I see - you get timeout accessing Cloudflare server on 54.230.86.161, so it seems that you are not able to reach it from your network. Are able to reach any of other Cloudflare CDN instances? 

Starting from next version 0.4.0 we will be deploying to [Jcenter](https://bintray.com/bintray/jcenter), but that is also served using Cloudflare CDN.

**Comment by tovbinm** [comment]
@zzdgit did it eventually work for you?

**Comment by zzdgit** [comment]
@tovbinm Thank you very much，I'm sure it was a network issue。But I am in China, and I need a VPN to access your address
