### ISSUE TITLE
Evaluate integration with Sparser library

### ISSUE THREAD

**Issue by tovbinm** [salesforce/TransmogrifAI#157]
**Problem**
Json parsing is slow and we should allow a better way.

**Solution**
Evaluate Sparser - https://dawn.cs.stanford.edu/2018/08/07/sparser/

1. Implement a JSON reader using Spark
2. Implement a JSON reader using Sparser
3. Evaluate performance 

**Alternatives**
?!

**Comment by tovbinm** [comment]
@hemanthvenkata is willing to work on this. Please let me know if you have any questions.

**Comment by dai-dao** [comment]
I'm working on this issue if no one is doing it. @tovbinm

**Comment by hemanthvenkata** [comment]
@tovbinm I did my analysis with various file sizes from 500 MB to 3GB which ranging rows from million to billion. Following are my finding:
1. sparser is more effective with operations like filter
2. It is mainly introduced to increase parsing time of raw data which is unstructured.

With that being said I didn't see much difference if we use sparser for structured data.
For using the sparser, we just need to change the format while reading files as `edu.stanford.sparser.json` from `json`.

As per my understanding, TransmogrifAI is more for structured data and I don't think we see much performance difference here with sparser.

Resources:
video: https://vimeo.com/274496506
sparser(https://dawn.cs.stanford.edu/2018/08/07/sparser/)

**Comment by tovbinm** [comment]
@hemanthvenkata thanks for sharing your findings. I will close this issue for now.
