### ISSUE TITLE
Can I use the best model for prediction by test data?

### ISSUE THREAD

**Issue by jdlzy** [salesforce/TransmogrifAI#158]
**Problem**
I I got the best model through the transmogriAI,But I don't konwn how to prediction the test set?

**Comment by tovbinm** [comment]
It's quite straight forward: 
```scala
val scores = model.setReader(scoringReader).score()
```
You can find more details in [our docs](https://docs.transmogrif.ai/en/stable/developer-guide/index.html?highlight=model.setReader#fitted-workflows).
