### ISSUE TITLE
Use TransmogrifAI with CDH 6.0

### ISSUE THREAD

**Issue by ffmm3** [salesforce/TransmogrifAI#173]
I want to use TransmogrifAI with CDH6.0, but encounter some problems.  After installation of TransmogrifAI following the quick start doc, I submit the Titanic example with spark-submit command, a classnotfound exception is thrower, which said class com.fasterxml.jackson.module.scala.modifiers.EithModule was not found. Then I found TransmogrifAI depends on jackson-module-scala_2.11-2.6.5.jar, and the class exists in this jar. But CDH depends on jackson-module-scala_2.11-2.9.5.jar, which not contains this class. So what should I do to tackle the problem and run the demo with CDH? Thxs!

**Comment by tovbinm** [comment]
@ffmm3 TransmogrifAI does not introduce jackson dependency directly, but uses the transitive jackson dependency from Spark. You can force a specific jackson version in your project as explained [here](https://github.com/salesforce/TransmogrifAI/issues/162). Let me know if it works for you.
