### ISSUE TITLE
Run in sbt

### ISSUE THREAD

**Issue by dai-dao** [salesforce/TransmogrifAI#174]
**Describe the bug**
I make a new Scala project using sbt. I simply use the exact code in the OpTitanicSimple example

I get this exception:

```
java.lang.AbstractMethodError
```
on line 

```
val prediction =
            BinaryClassificationModelSelector.withTrainValidationSplit(
                modelTypesToUse = Seq(OpLogisticRegression)
            ).setInput(survived, finalFeatures).getOutput()
```

**To Reproduce**
Here's my build.sbt file:

```
name := "auto-titanic"

version := "0.1"

// This is important for Transmorgrif and Spark
scalaVersion := "2.11.12"

resolvers += Resolver.jcenterRepo
resolvers += Resolver.mavenCentral

// TransmogrifAI core dependency
libraryDependencies += "com.salesforce.transmogrifai" %% "transmogrifai-core" % "0.4.0"
libraryDependencies += "org.apache.spark" %% "spark-core" % "2.3.2"
libraryDependencies += "org.apache.spark" %% "spark-sql" % "2.3.2"
libraryDependencies += "org.apache.spark" %% "spark-mllib" % "2.3.2"
```

Additionally, I also change the SparkContext line to:
```
implicit val spark = SparkSession.builder.config("spark.master", "local").getOrCreate()
```

Java version is 1.8.0_181

**Expected behavior**
To run normally as in the provided example

**Logs or screenshots**
If applicable, add logs or screenshots to help explain your problem.

**Additional context**

**Comment by tovbinm** [comment]
Hmm, this not be the case. Try running our Helloworld sbt based project - https://github.com/salesforce/transmogrifai-helloworld-sbt

**Comment by dai-dao** [comment]
Can you show me how to set up debugging for this project, as well as the gradle project? Currently, I'm doing this for the sbt project:

```
export SPARK_SUBMIT_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=4000

spark-submit --class com.salesforce.hw.OpTitanicSimple target/scala-2.11/transmogrify-helloworld_2.11-0.1-SNAPSHOT.jar 
```

and then set up Remote configuration to attach to the JVM. I get this error:

```
Exception in thread "main" java.lang.NoClassDefFoundError: com/salesforce/op/features/FeatureLike
```

**Comment by tovbinm** [comment]
@dai-dao whn you run the project with `spark-submit --class` you need to have all the TransmogrifAI jars in your class path or build and uber jar - https://github.com/eed3si9n/sbt-assembly

**Comment by dai-dao** [comment]
Thanks, I got it working. Closing the issue now.
