### ISSUE TITLE
TransmogirfAI build issues 

### ISSUE THREAD

**Issue by janardh461** [salesforce/TransmogrifAI#189]
Alternatively you can disable this build feature completely by removing this line https://github.com/salesforce/TransmogrifAI/blob/master/build.gradle#L26
from your build.gradle file.

I have commented line 26 and tried to build again:. Now the build fails at line 164. 
The trace is given below: 

FAILURE: Build failed with an exception.
* Where:
Build file '/home/cuda/TransmogrifAI/build.gradle' line: 164
* What went wrong:
A problem occurred evaluating root project 'transmogrifai'.
> Could not get unknown property 'createVersionProperties' for root project 'transmogrifai' of type org.gradle.api.Project.

In Line 164 , I find the following
Line 164:
 if (System.getenv("CI") != 'true') {
        jar.dependsOn(createVersionProperties)
    }

I set the envirnment variable CI to false. Then I get the following error at line 231:

shadowJar.dependsOn(createVersionProperties)

The variable createVersionProperties is is required by the script. Please help me to find out the most viable solution to work around this problem,.

**Comment by tovbinm** [comment]
You can completely remove the following lines from `build.gradle`:
1. Line 26 - `apply from: 'gradle/version-properties.gradle'`
2. Lines 163-165:
```groovy
if (System.getenv("CI") != 'true') {
   jar.dependsOn(createVersionProperties)
}
```
2. Line 231 - `shadowJar.dependsOn(createVersionProperties)`

**Comment by tovbinm** [comment]
I pushed a fix to master branch to avoid failing on missing git command.
