### ISSUE TITLE
Error: Could not find or load main class com.salesforce.op.cli.CLI

### ISSUE THREAD

**Issue by PoojaG20** [salesforce/TransmogrifAI#191]
I am working on windows......  for building I used in Windows command prompt -
**gradlew.bat cli:shadowJar**
then for alias i used-
DOSKEY transmogrifai=java -cp $OP_HOME/cli/build/libs/* com.salesforce.op.cli.CLI

But when i am trying to 
> generate using transmogrifai 

I am getting error as -
**Error: Could not find or load main class com.salesforce.op.cli.CLI**

Any help will be appreciated and please let me know if i did anything wrong

**Comment by tovbinm** [comment]
For windows solution read this thread - https://github.com/salesforce/TransmogrifAI/issues/182

**Comment by PoojaG20** [comment]
I followed that thread only and getting error what he was getting as - 

**transmogrifai gen --input "path\TransmogrifAI\test-data\PassengerDataAll.csv" --id passengerId --response survived --schema "path\TransmogrifAI\test-data\PassengerDataAll.avsc" Titanic**

> transmogrifai: TransmogrifAI CLI
> Usage: transmogrifai [gen] [options] <args>...
> 
>   --help
> 
> Command: gen [options] name
> Generate a new TransmogrifAI project
>   name                     Name for the TransmogrifAI project (should be in CamelCase) [required]
>   --input <value>          Input file for the TransmogrifAI project [required]
>   --id <value>             Name for the ID field [required]
>   --response <value>       Feature name to predict [required]
>   --answers <value>        answers to generator questions [optional]
>   --overwrite              allowed to overwrite existing project directory
>   --schema <value>         Avro schema to use for objects; required unless you specify --auto
>   --auto <value>           Automatic detection of data schema (you need to provide a name);
> need this one or a schema file. Experimental feature.
> wrong arguments


Though i have defined schema then also getting this error

**Comment by tovbinm** [comment]
Hmm, we are using [scopt](https://github.com/scopt/scopt) to parse command line arguments into our process. It's possible that there is some kind of a problem with it when used on windows. Unfortunately I dont have a windows machine to reproduce it. 

Perhaps instead of using codegen you can start from an existing Helloworld project - https://docs.transmogrif.ai/en/stable/examples/Titanic-Binary-Classification.html?
