### ISSUE TITLE
Automatic Feature Engineering result to DataFrame 

### ISSUE THREAD

**Issue by shubamgupta** [salesforce/TransmogrifAI#194]
I want to see the result after running **.transmogrify()** so as to check what is the final dataset on which we will be training our model. 
I tried all the possible functions included in Feature class but I only got the stages involved in preprocessing.
 e.g. 
> -- combVec
> |    +-- smartTxtVec
> |    |    +-- ConcatText(column1)
> |    |    +-- ConcatText(column2)

but _I need the final dataset which is created after the transmogrify() like how each column is transformed_

**Comment by tovbinm** [comment]
Workflow and model have method called `computeDataUpTo` which would do exactly what you need. Additionally model allows you to retrieve all intermediate and final feature then calling `score` method. Read more here - https://docs.transmogrif.ai/en/stable/developer-guide/index.html#fitted-workflows
Scaladoc - https://scaladoc.transmogrif.ai/index.html#com.salesforce.op.OpWorkflowModel@computeDataUpTo(feature:com.salesforce.op.features.OPFeature,persistEveryKStages:Int)(implicitspark:org.apache.spark.sql.SparkSession):org.apache.spark.sql.DataFrame

**Comment by shubamgupta** [comment]
@tovbinm I think you didn't get my question correctly. Actually what I wanted is like in python suppose I am having 3 Columns: 1. Id 2. Gender 3. Education. Now, when I load this to data frame and do the preprocessing steps after that let suppose I got 5 columns. Now, I can save that data frame again in csv format.
Is that possible in transmogrifai to save the preprocessed data in csv or excel format.

**Comment by tovbinm** [comment]
We currently dont have a function to save dataframe as csv, but we have a function to save/load to/from avro like this:
```
import com.salesforce.op.utils.spark.RichDataset._

implicit spark: SparkSession = ???
val dataframe: Dataframe = ???
dataframe.saveAvro(path) // save dataframe to a file
val loaded: Dataframe = loadAvro(path) // load from a file
```

You can perhaps looks into our implementation and implement a version for exporting into a csv file.

**Comment by tovbinm** [comment]
Also, if you just want to "see" the dataframe you can simply do `dataframe.show(truncate = false)` and it will print out a sample of rows for you.

**Comment by shubamgupta** [comment]
@tovbinm Thank you for your help. It really helps me a lot. One more thing regarding the same. Is it possible to see sample rows after **val featureVector = features.transmogrify()** stage. or can I convert this featureVerctor back to dataframe.

**Comment by shubamgupta** [comment]
@tovbinm Thank you for your help.

**Comment by shubamgupta** [comment]
@tovbinm I have created different models using transmogrif ai. One thing I noticed is when I run my code 4-5 times, each time the results vary even though the code and dataset is same. Can you tell me the reason why it is happening?

**Comment by shubamgupta** [comment]
@tovbinm I tried this too fixing the random seed for my dataset. But I still see the variations in the result. I tried to explore the issue what I found different is instancePerNode and maxDepth parameter is varying when I run the above code. But why, this is changing if we claim it should return the best parameter.

**Comment by tovbinm** [comment]
I think you are talking about the Random Forest? It also has a random seed parameter which you would need to set:
```scala
 val rf = new OpRandomForestClassifier().setSeed(randomSeed)
 val rfParams = new ParamGridBuilder()
        .addGrid(rf.maxDepth, DefaultSelectorParams.MaxDepth)
        .addGrid(rf.impurity, DefaultSelectorParams.ImpurityClass)
        .addGrid(rf.maxBins, DefaultSelectorParams.MaxBin)
        .addGrid(rf.minInfoGain, DefaultSelectorParams.MinInfoGain)
        .addGrid(rf.minInstancesPerNode, DefaultSelectorParams.MinInstancesPerNode)
        .addGrid(rf.numTrees, DefaultSelectorParams.MaxTrees)
        .addGrid(rf.subsamplingRate, DefaultSelectorParams.SubsampleRate)
        .build()

val modelsAndParameters = Seq(rf -> rfParams)
val prediction = BinaryClassificationModelSelector
    .withCrossValidation(splitter = Option(splitter), seed = randomSeed, modelsAndParameters = modelsAndParameters)
    .setInput(/* your features */)
    .getOutput()
```

**Comment by tovbinm** [comment]
Just YFI, in this #199 PR I am exposing our default models so it would be easier to modify.
