### ISSUE TITLE
TransmogrifAI on Jupyter

### ISSUE THREAD

**Issue by tovbinm** [salesforce/TransmogrifAI#211]
**Problem**
Allow using TransmogrifAI in [Jupyter](https://jupyter.org).

**Solution**
It would be great to have a step by step tutorial (and also perhaps a script) on how to setup Jupyter notebook with TransmogrifAI, Scala and Apache Spark. 

**Alternatives**
NA

**Comment by rajdeepd** [comment]
@tovbinm i was exploring doing this with Apache Toree, what is the best way to load the transmogrify dependencies into toree kernel? 

Loaded the five transmogrify specific jars from build/lib folder but it is not sufficient

**Comment by tovbinm** [comment]
Potentially. It would need some research on what's the best kernel to use. Some of thing I found:
https://github.com/deanwampler/spark-scala-tutorial
https://github.com/deanwampler/JustEnoughScalaForSpark
https://github.com/almond-sh/almond

**Comment by rajdeepd** [comment]
1. https://github.com/deanwampler/spark-scala-tutorial
   https://github.com/deanwampler/JustEnoughScalaForSpark
Both use apache toree inside a docker container. 

I was able to run basic spark app in toree.
To add external libraries we can use %AddJar feature, but it wont load app dependencies, any suggestion?

%AddJar https://s3.amazonaws.com/transmogrify/transmogrifai-0.6.0-SNAPSHOT.jar
%AddJar https://s3.amazonaws.com/transmogrify/transmogrifai-core_2.11-0.5.0.jar
%AddJar https://s3.amazonaws.com/transmogrify/transmogrifai-features_2.11-0.5.0.jar
%AddJar https://s3.amazonaws.com/transmogrify/transmogrifai-readers_2.11-0.5.0.jar
%AddJar https://s3.amazonaws.com/transmogrify/transmogrifai-utils_2.11-0.5.0.jar

**Comment by tovbinm** [comment]
Interesting. Can you load jars from Maven central?

**Comment by rajdeepd** [comment]
Yes here is an example

%AddDeps org.joda joda-money 0.11 --transitive --trace --verbose

**Comment by tovbinm** [comment]
@ivanbogdanov is looking into it as well. you guys should collaborate @rajdeepd  ;)

**Comment by rajdeepd** [comment]
@tovbinm sure @ivanbogdanov please let me know how we take this forward

**Comment by ivanbogdanov** [comment]
@tovbinm I am using almond.sh to make it work locally with Jupyter

**Comment by timsetsfire** [comment]
Had a lot of success using beakerx.  Magics allowed to pull spark and transmogrifai from maven. Used this recently at a local Meetup. GitHub.com/timsetsfire/pgh-ds-automl

**Comment by rajdeepd** [comment]
Getting this error in Toree on running following code:

val survived = FeatureBuilder.RealNN[Passenger].extract(_.survived.toRealNN).asResponse

Message: <console>:102: error: Symbol 'type <none>.sourcecode.Name' is missing from the classpath.
This symbol is required by 'value com.salesforce.op.features.FeatureBuilder.name'.

**Comment by rajdeepd** [comment]
> Had a lot of success using beakerx. Magics allowed to pull spark and transmogrifai from maven. Used this recently at a local Meetup. https://github.com/timsetsfire/pgh-ds-automl/blob/master/README.md
> 
> One thing worth mentioning I had all sorts of problems with openjdk 11. The issues were resolved by using 8
> 
> http://beakerx.com

@timsetsfire this is great, i was able to run the samples.
