### ISSUE TITLE
Unable to create features dynamically.

### ISSUE THREAD

**Issue by shivam1892** [salesforce/TransmogrifAI#228]
**Describe the bug**
I was trying to run the sample examples given [here](https://github.com/salesforce/transmogrifai-helloworld-sbt). In examples we need to define schema file (Case class) for the data supplied to Transmogrifai reader Eg: In Boston Housing price. But, I would like to know, if I can work with Transmogrifai without defining the schema for the data (Similar to inferSchema in Spark), which automatically infers the schema from the data provided example from CSV.

**To Reproduce**
Minimal set of steps or code snippet to reproduce the behavior

**Expected behavior**
I just need to provide the CSV file or any other file, it should create data-frame by inferring schema and run the algorithms on top of that.

**Logs or screenshots**
If applicable, add logs or screenshots to help explain your problem.

**Additional context**
I know there is functionality where we can use Avro schema to create Schema class which generates java class for schema, but again we need to define FeatureBuilders on top of that Eg: Iris data multi-classification.

Can it be done without defining these schema i.e By inferring schema & create feature builder automatically and run the algorithms on top of that.
Example of inferSchema from csv file in Spark Scala.
```
val df = sqlContext.
                  read.
                  format("com.databricks.spark.csv").
                  option("header", "true").
                  option("inferSchema", "true").
                  load(sampleData)
```

**Comment by shivam1892** [comment]
I have also tried [this](https://github.com/salesforce/transmogrifai-helloworld-sbt/blob/master/src/main/scala/com/salesforce/hw/titanic/OpTitanicMini.scala) example where Feature engineering is done automatically.
Here I removed the case class (Passanger) from the code and tried to generate it with Avro dynamically. But I am getting compile time error as shown:
![screenshot from 2019-02-18 16-43-38](https://user-images.githubusercontent.com/31059856/52947329-61309780-339c-11e9-8843-121d199c3e0c.png)

Kindly provide the solution to achieve this functionality.

**Comment by tovbinm** [comment]
Yes, we have a CSV reader that allows inferring schema automatically. See [CSVAutoReader](https://github.com/salesforce/TransmogrifAI/blob/master/readers/src/main/scala/com/salesforce/op/readers/CSVAutoReaders.scala).

Here is an example way to use it:
```scala
val autoReader = new CSVAutoReader[GenericRecord](readPath, _.get("id").toString)
```
Notes:
1. You can use any other more specific type instead of `GenericRecord` if you'd like. 
2. You can customize CSV parsing options using `CSVOptions` argument
3. You can also customize the names of the field by passing in `headers`

Please let me know if it works for you.

**Comment by shivam1892** [comment]
Hi thanks for help,

I am trying to to read with CSVAutoReader for that i replace
```scala
val passengersData = DataReaders.Simple.csvCase[Passenger](pathToData, key = _.id.toString).readDataset()(spark, newProductEncoder).toDF()
```
with 
```scala
val passengersData = new CSVAutoReader[GenericRecord](pathToData, key = _.get("id").toString, headers =
      Seq("id", "survived", "pClass", "name", "sex", "age", "sibSp", "parCh", "ticket", "fare", "cabin", "embarked")).read()(spark)
```
in [this](https://github.com/salesforce/transmogrifai-helloworld-sbt/blob/master/src/main/scala/com/salesforce/hw/titanic/OpTitanicMini.scala) example.

but next step 
```scala
val (survived, features) = FeatureBuilder.fromDataFrame[RealNN](passengersData, response = "survived")
    val featureVector = features.transmogrify()
```
creates the features from dataframe but in CSVAutoReader read method is convertible to Dataframe.
This is giving compile time error as shown in screenshot.
![screenshot from 2019-02-19 14-38-28](https://user-images.githubusercontent.com/31059856/53003025-0f4b4880-3454-11e9-9bbd-212ba2c4f65e.png)

It will be great if you can provide the working example for this, as I am not able to find on provided hello-world examples.

**Comment by tovbinm** [comment]
In general readers only allow reading typed data in an RDD using [`read()`](https://github.com/salesforce/TransmogrifAI/blob/master/readers/src/main/scala/com/salesforce/op/readers/DataReader.scala#L81) method or materializing a dataframe for a provided set of features using [`generateDataFrame()`](https://github.com/salesforce/TransmogrifAI/blob/master/readers/src/main/scala/com/salesforce/op/readers/Reader.scala#L168) method.

What I understand from your case is that you want to have **both** feature definitions and data reader be created automatically. The only way to currently allow that is to use our cli tool as explained [here](https://docs.transmogrif.ai/en/stable/examples/Bootstrap-Your-First-Project.html). You can try using `--auto` flag to automatically detect schema prior to generating features (though it's experimental).

**Comment by shivam1892** [comment]
Yes So, I would like to raise a feature request, in which we can convert spark Dataframe to TransmogrifAI Dataframe which we can directly pass to 
```scala
val (survived, features) = FeatureBuilder.fromDataFrame[RealNN](transmogrifConvertedDFfromSpark, response = "survived")
```
and to the workflow
```scala
val model = new OpWorkflow().setInputDataset(transmogrifConvertedDFfromSpark).setResultFeatures(prediction).train()(spark)
```

**Comment by tovbinm** [comment]
`FeatureBuilder.fromDataFrame` allows you to pass in a dataframe and infer primitive feature types but we still haven't implemented it for more advanced types #64

**Comment by shivam1892** [comment]
Here is the snapshot of the code I am trying to run  using spark dataframe. (I have added column names to the CSV file)
```scala
val df = spark.read.format("com.databricks.spark.csv").option("header", "true").option("inferSchema", "true").load(pathToData)
val (survived, features) = FeatureBuilder.fromDataFrame[RealNN](df, response = "survived")
``` 
df is the spark dataframe & I get the following error. (I am assuming the primitive data type 'RealNN' is implemented because according the error below, Transmogrifai is not converting integral type to RealNN type)
```
Exception in thread "main" java.lang.RuntimeException: Response feature 'survived' is of type com.salesforce.op.features.types.Integral, but expected com.salesforce.op.features.types.RealNN
```

**Comment by tovbinm** [comment]
You would need to apply a column transformation on dataframe using `udf` to convert `survived` into Double.

**Comment by shivam1892** [comment]
Yes Now its running, Thanks @tovbinm 

One more thing I want to know In case of multi-class classification Eg ("a","b","c") 3 classes, I want to follow same procedure, There should I provide string indexes as response Eg (1,2,3) or should it be one-hot encoded Eg ([1,0,0], [0,1,0], [0,0,1]).
When I give string indexes as response, then algorithm works fine and gives the output, so
1) Does Transmogriai internally do this one-hot encoding step, because if it does not then it will consider the numerical ordering of indexes in the algorithm which is not good for algorithm.
2) If not then how to provide the response variable in multi-class classification problem.

**Comment by tovbinm** [comment]
We don't modify the label automatically and yes, you should do index the response feature for multi class. E.g.
```scala
val response: FeatureLike[PickList] = ...
val indexed: FeatureLike[RealNN] = response.indexed()
```
