### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by lei6315** [salesforce/TransmogrifAI#234]
**Describe the bug**
I use ./gradlew compileTestScala installDist to build the code  failed!

my env

```
linux 7
spark 2.3.3
java 8
grade 5.2
```

**Logs or screenshots**
```
FAILURE: Build failed with an exception.

* Where:
Build file '/data0/users/gaolei7/weibo_code/TransmogrifAI/build.gradle' line: 14

* What went wrong:
Plugin [id: 'com.commercehub.gradle.plugin.avro', version: '0.8.0'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'com.commercehub.gradle.plugin.avro:com.commercehub.gradle.plugin.avro.gradle.plugin:0.8.0')
  Searched in the following repositories:
    Gradle Central Plugin Repository

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 46s

```
please help me, thanks!

**Comment by tovbinm** [comment]
The plugin is definitely there - https://plugins.gradle.org/m2/com/commercehub/gradle/plugin/avro/com.commercehub.gradle.plugin.avro.gradle.plugin/0.8.0/

Make sure you can access it from you machine and there is no firewall blocking it.

**Comment by lei6315** [comment]
Thank you very much, I tried several times still build failed! Can I download this plugin by hand and where should I place this jar file in linux system, thanks.

**Comment by tovbinm** [comment]
Probably. Try searching for a similar issue on https://discuss.gradle.org/
