### ISSUE TITLE
Varying accuracy on Titanic dataset over different runs

### ISSUE THREAD

**Issue by py-ranoid** [salesforce/TransmogrifAI#253]
**Describe the bug**
Multiple runs of the Titanic classifier seem to produce different metrics without any change to the code. 

**To Reproduce**
Compile and Run the helloworld Titanic example multiple times 

**Expected behavior**
Consistent or at least similar models ought to be generated across all runs.

**Logs or screenshots**
The precision of 4th run is almost 10% more than the others. 
```
  "Precision" : 0.7420382165605095,
  "Recall" : 0.6812865497076024,
  "F1" : 0.7103658536585367,
  "AuROC" : 0.8439320827874179,
  "AuPR" : 0.814893718753765,
  "Error" : 0.2132435465768799,
  "TP" : 233.0,
  "TN" : 468.0,
  "FP" : 81.0,
  "FN" : 109.0,

  "Precision" : 0.7423312883435583,
  "Recall" : 0.7076023391812866,
  "F1" : 0.7245508982035929,
  "AuROC" : 0.8461290597471213,
  "AuPR" : 0.819708607558705,
  "Error" : 0.20650953984287318,
  "TP" : 242.0,
  "TN" : 465.0,
  "FP" : 84.0,
  "FN" : 100.0,

  "Precision" : 0.739938080495356,
  "Recall" : 0.6988304093567251,
  "F1" : 0.718796992481203,
  "AuROC" : 0.8449786427209492,
  "AuPR" : 0.8178952552703507,
  "Error" : 0.20987654320987653,
  "TP" : 239.0,
  "TN" : 465.0,
  "FP" : 84.0,
  "FN" : 103.0,

  "Precision" : 0.8310344827586207,
  "Recall" : 0.7046783625730995,
  "F1" : 0.7626582278481013,
  "AuROC" : 0.8892324161953149,
  "AuPR" : 0.8608911515452313,
  "Error" : 0.16835016835016836,
  "TP" : 241.0,
  "TN" : 500.0,
  "FP" : 49.0,
  "FN" : 101.0,
```

**Comment by tovbinm** [comment]
Model performance can vary depending how the random splits between training and tests sets are done. Considering how little data you have such fluctuations are normal.

**Comment by py-ranoid** [comment]
I set the [default seed](https://github.com/salesforce/TransmogrifAI/blob/master/core/src/main/scala/com/salesforce/op/stages/impl/tuning/Splitter.scala#L123) to 100, instead of `util.Random.nextLong` but I'm still getting inconsistent metrics. While it is posssible, it seems a bit odd for the AUC to rise by 0.04 on merely changing the train-test split.

**Comment by tovbinm** [comment]
To eliminate the most of the randomness you need to pass the seed into model selector and splitter, e.g.:
```scala
val seed = 42L
BinaryClassificationModelSelector.withCrossValidation(
   splitter = Option(DataSplitter(seed = seed)), seed = seed
)
```
