### ISSUE TITLE
Replace Joda with Java 8 native Date Time 

### ISSUE THREAD

**Issue by wsuchy** [salesforce/TransmogrifAI#287]
**Problem**
Since Java 8 was introduced there is no need to use Joda as it has been replaced the native Date-Time API.

**Solution**
Ideally greping and replacing the text should work (mostly)

**Additional context**
Need to check if de/serializing will still work.

**Comment by tovbinm** [comment]
Not: I think there is no cost for us to useit, since it might already be a spark transitive dependency. If no, then perhaps we can remove it.

**Comment by Vizienteling948** [comment]
Experts in Lightning development are becoming more popular. The salary depends on the Salesforce specialization and starts at $89,135 a Salesforce Administrator while for [Salesforce lightning developer salary](https://www.ergonized.com/blog/salesforce-vacancies-job-market-research/) rates start at $116,894 per year. Moreover, Salesforce Developer Lightning experience is valued on the market, so there are higher chances of getting a job offer for the specialists who are acquainted with Lightning pecularities.

**Comment by trynnaBeADev** [comment]
Is this issue still relevant ?? If yes, Can i work on this 
If not, I see some commits merged. Can this be labelled as closed

**Comment by tovbinm** [comment]
I think the effort was abandoned at some point.
Here is the latest PR on it - https://github.com/salesforce/TransmogrifAI/pull/329
