### ISSUE TITLE
PySpark Support

### ISSUE THREAD

**Issue by oelesinsc24** [salesforce/TransmogrifAI#301]
Does TransmorgrifAI support PySpark or is will this be supported in the future or is there a workaround for usage in PySpark?

Thanks in advance!

**Comment by py-ranoid** [comment]
Hey @oelesinsc24, TransmogrifAI is written in Scala and doesn't support PySpark yet. 

While I can't comment on it officially, I may implement a PySpark wrapper in the future to use TransmogrifAI with Python. If it helps, this is how I thought I'd go about it :
- [Passing dataframes between Scala Spark and PySpark](https://www.crowdstrike.com/blog/spark-hot-potato-passing-dataframes-between-scala-spark-and-pyspark/)
- [Spark - Calling Scala code from PySpark](https://aseigneurin.github.io/2016/09/01/spark-calling-scala-code-from-pyspark.html)
- [Scala Spark UDFs in Python](https://sigdelta.com/blog/scala-spark-udfs-in-python/)

If I may ask, which methods of TransmogrifAI were you hoping to run with PySpark?

**Comment by oelesinsc24** [comment]
Thanks for the prompt feedback

**Comment by OElesin** [comment]
I'm hoping to make TransmogrifAI available on AWS SageMaker, mainly the auto feature extraction.

**Comment by tovbinm** [comment]
@OElesin that would be great! I think it was already done once. Perhaps @wsuchy @gerashegalov  @Jauntbox can share the recipe on how to do it?

**Comment by OElesin** [comment]
Any comments here!?
