### ISSUE TITLE
Regression seems not to end in cluster but succeed in standalone computer.

### ISSUE THREAD

**Issue by hzrt123** [salesforce/TransmogrifAI#338]
I run a regression test. 

First I test in a standalone computer, it succeeds in a few minutes. 

Then I test in a cluster and it would not end even after a night.

What is the possible reason?    BTW, how can I set a time limit or iteration limit for such long runs?

Thanks.

**Comment by tovbinm** [comment]
Troubleshooting Spark jobs can be tricky. I would need some details on how you submit your Spark job:
1. Is it YARN or Spark native cluster?
2. What are the settings you use? (driver memory, executor memory, num of executors etc.) 
3. What is the size of the data? How many partitions?
4. How many partitions?
5. How many features are you materializing?
6. What are model selector setting you are using?

**Comment by hzrt123** [comment]
I use the YARN cluster.

The command is: spark-submit --master yarn --deploy-mode cluster --num-executors 4 --executor-cores 8 --executor-memory 16g

The  dataset is as in: https://archive.ics.uci.edu/ml/datasets/SGEMM+GPU+kernel+performance

size: 241600 X 18

The partition should be default setting.

The columns are: 
```
MWG,NWG,KWG,MDIMC,NDIMC,MDIMA,NDIMB,KWI,VWM,VWN,STRM,STRN,SA,SB,Run1 (ms),Run2 (ms),Run3 (ms),Run4 (ms)
```

I drop the last 3 columns. The codes is as following:

```
object OpTitanicMini {

  def main(args: Array[String]): Unit = {
    LogManager.getLogger("com.salesforce.op").setLevel(Level.ERROR)

    implicit val spark = SparkSession.builder.config(new SparkConf()).getOrCreate()
    import spark.implicits._

    // Read Titanic data as a DataFrame
    val pathToData = Option(args(0))


    val passengersData1 = spark.read
      .option("header", "true") // if you have the header in your csv file to make the schema match
      .option("inferSchema", "true") // allows to infer data types by Spark
      // .schema(schema)
      .csv(pathToData.get)

    passengersData1.printSchema()
    passengersData1.show()

    val passengersData2 = passengersData1.drop("Run2 (ms)", "Run3 (ms)", "Run4 (ms)")
    passengersData2.printSchema()
    passengersData2.show(100)

    // Use passengerData, and Modify response

    val passengersData = passengersData2


    // Automated feature engineering
    val (survived, features) = FeatureBuilder.fromDataFrame[RealNN](passengersData, response = "Run1 (ms)")
    val featureVector = features.transmogrify()

    // Automated feature selection
    val checkedFeatures = survived.sanityCheck(featureVector, checkSample = 1.0, removeBadFeatures = true)

    // Automated model selection
    val prediction = RegressionModelSelector
      .withCrossValidation(modelTypesToUse = Seq(OpGBTRegressor, OpRandomForestRegressor))
      .setInput(survived, checkedFeatures).getOutput()
    val model = new OpWorkflow().setInputDataset(passengersData).setResultFeatures(prediction).train()

    println("Model summary:\n" + model.summaryPretty())
  }
}
```

**Comment by tovbinm** [comment]
Try bumping the driver memory and cores as well by passing `--driver-memory 32g --driver-cores 2` as well (thanks for pointing that out @snabar )

**Comment by hzrt123** [comment]
Bravo!   I tried --driver-memory 16g --driver-cores 2, and it could work.

**Comment by Neeraja2303** [comment]
what does these attributes mean <html>
<body>


MWG | NWG | KWG | MDIMC | NDIMC | MDIMA | NDIMB | KWI | VWM | VWN | STRM | STRN | SA | SB | Run1 (ms) | Run2 (ms) | Run3 (ms) | Run4 (ms)
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
