### ISSUE TITLE
Not serializable exception during `computeFeatureStats`

### ISSUE THREAD

**Issue by alkersan** [salesforce/TransmogrifAI#362]
**Description**
Serializability issue during one of the stages of model training:
```
... 
(TID 3067704) had a not serializable result: scala.collection.immutable.MapLike$$anon$2
Serialization stack:
    - object not serializable (class: scala.collection.immutable.MapLike$$anon$2)
...
```

Stacktrace leads to `com.salesforce.op.filters.PreparedFeatures#summaries` method, which is called from `com.salesforce.op.filters.RawFeatureFilter#computeFeatureStats`. The usage 
 of `mapValues` leads to a non serializable Map, which is a long standing [scala bug](https://github.com/scala/bug/issues/7005).

I've attempted to fix that just by adding a `.map(identity)`, which resolved the issue, i.e.:
```
predictors.mapValues(Summary(_)).map(identity)
```
 Not sure about "correct" way of dealing with that

**Additional context**
Transmogrify version: `0.5.1` & `0.5.2`. Though it seems to be applicable to current `master`, as the related code didn't change since then.

**Comment by tovbinm** [comment]
Thanks for reporting this. Fixed in #363
