### ISSUE TITLE
DataSplitter and DataCutter throws error in 0.6.0

### ISSUE THREAD

**Issue by rajdeepd** [salesforce/TransmogrifAI#369]
**Describe the bug**
Getting the following error while executing 

```
   val splitter = DataSplitter(seed = randomSeed) 
```
for Version 0.6.0, this seems to have worked in 0.5.3

```
  java.lang.AbstractMethodError
    at org.apache.spark.ml.param.Params$class.$init$(params.scala:868)
    at com.salesforce.op.stages.impl.tuning.Splitter.<init>(Splitter.scala:56)
    at com.salesforce.op.stages.impl.tuning.DataSplitter.<init>(DataSplitter.scala:62)
   at com.salesforce.op.stages.impl.tuning.DataSplitter$.apply(DataSplitter.scala:51)
   ... 58 elided
```

**To Reproduce**
Run the TransmogrifAI samples with the following statement above

**Expected behavior**
an exception should not be shown and class should get initialized

**Logs or screenshots**
none

**Additional context**
none

**Comment by rajdeepd** [comment]
@tovbinm

**Comment by tovbinm** [comment]
This kind of error usually originates from an invalid Spark version being used. Are you sure that you are using Spark 2.3.2?

Please refer to compatibility matrix for version matching - https://github.com/salesforce/TransmogrifAI/blob/master/README.md#adding-transmogrifai-into-your-project

**Comment by rajdeepd** [comment]
I was using 2.4.3 with 2.3.2 it is working
