### ISSUE TITLE
Confused with 'splitter', 'trainRatio', 'validation', 'test'

### ISSUE THREAD

**Issue by hzrt123** [salesforce/TransmogrifAI#388]
I'm trying to understand the workflow logic:

```
  def withCrossValidation(
    splitter: Option[DataCutter] = Option(DataCutter()),
    numFolds: Int = ValidatorParamDefaults.NumFolds,
```

```
  def withTrainValidationSplit(
    splitter: Option[DataCutter] = Option(DataCutter()),
    trainRatio: Double = ValidatorParamDefaults.TrainRatio,
```

```
  /**
   * Creates Train Validation Splits For TS
   *
   * @param stratifyCondition condition to do stratify ts
   * @param dataset           dataset to split
   * @param label             name of label in dataset
   * @param splitter          used to estimate splitter params prior to ts
   * @return Array[(Train, Test)]
   */
  private[op] override def createTrainValidationSplits[T](
    stratifyCondition: Boolean,
    dataset: Dataset[T],
    label: String,
    splitter: Option[Splitter]
```

First, I don't know the relationship between 'trainRatio' and 'splitter'. 

Base on the comment, the 'Train Validation' split means, the dataset has 2 parts: Train, and Test ?

'Test' means 'Holdout'?   And there is no 'Evaluation' set ?

The output usually contains 'Train score' and 'Holdout score'? Is there any 'Evaluation score'?

**Comment by hzrt123** [comment]
I mean the usual cut is (TrainSet, EvaluationSet, HoldoutSet), or (KFold_CV_Sets, HoldoutSet).

Is it what in Transmogrif ?

**Comment by tovbinm** [comment]
You are correct. For TV split it's going to be: train set, eval set and holdout set.
For CV there are going to be: k-fold sets (train/test permutations) and holdout set.

**Comment by hzrt123** [comment]
To confirm, 

1.   splitter =  HoldoutSet  /  (TrainSet + EvaluationSet)  
              or    HoldoutSet  /  KFold_CV_Sets

      trainRatio = TrainSet / EvaluationSet)       numFolds =   fold of KFold_CV_Sets


2.  summaryPretty() shows 'train score' and 'holdout score',   so they refer to EvaluationSet  and HoldoutSet respectively ?


3.  I use the obtained model to predict new data, like:
            model.setInputSet( New Data ).scoreAndEvaluate()

     So the New Data is supposed to be with No split / cut  at all (even though the default splitter and trainRatio exist)?


Hope for your answers. Thanks.
