### ISSUE TITLE
why does not linear svc model contain "probability"s in the output of "score()" function？

### ISSUE THREAD

**Issue by liuxiaodong008008** [salesforce/TransmogrifAI#396]
I found linear svc model does not contain `probability`s in the output of `score()` function.
And if linear svc does not have `probability`s, how do TransmogrifAI calculate `AuRoC` in the `summary()`?

**Comment by tovbinm** [comment]
The probability is not provided by the underlying `LinearSVCModel` Spark model. 

When computing metrics such as aupr, auroc, error, precision, recall, f1 only the label, prediction and raw prediction values are being used. E.g. - https://github.com/salesforce/TransmogrifAI/blob/master/core/src/main/scala/com/salesforce/op/evaluators/OpBinaryClassificationEvaluator.scala#L126)
