### ISSUE TITLE
Get/set output name of stage

### ISSUE THREAD

**Issue by DLT1412** [salesforce/TransmogrifAI#431]
How to get output name of stage, or set output column like `setOutputCol` in spark transformer/estimator.

**Comment by tovbinm** [comment]
Each stage sets the output feature name automatically based on it's ID. You can rename the output feature using the `alias` shortcut as follows:
```scala
val textFeature: FeatureLike[Text] = ???
val tokens: FeatureLike[TextList] = textFeature.tokenize().alias() // the output feature name is 'tokens'
// or explicitly
val tokens: FeatureLike[TextList] = textFeature.tokenize().alias("tokens")  // the output feature name is 'tokens'
```
