### ISSUE TITLE
how to use Weak type???

### ISSUE THREAD

**Issue by rudyMcgee** [salesforce/TransmogrifAI#439]
Recently I am building machine learning platform, I want to use TransmogrifAI for automl, but the data type is uncertain,  like this code:

val passengersData = DataReaders.Simple.csvCase[???](path = pathToData).readDataset().toDF()

"???" maybe case class , RealNN,or Text,  so I can't use strong type,

pls help me, ty

**Comment by tovbinm** [comment]
I am not following, what is the question you are asking?

**Comment by tovbinm** [comment]
Is this still relevant? @rudyMcgee
