### ISSUE TITLE
Apache Spark 2.4.X compatible version

### ISSUE THREAD

**Issue by asoriano-stratio** [salesforce/TransmogrifAI#443]
Hi!
I have seen that some work has been done in order to update Spark version to 2.4.X. (but seems that it is freezed).

I would like to know if this update is still in the Roadmap and if there exists an estimation about when it can be completed.

Thanks!

**Comment by tovbinm** [comment]
We can make a special version release for Spark 2.4. 

@leahmcguire when is the next time you were planning to make a release?

**Comment by nicodv** [comment]
@asoriano-stratio , we're actually working on this behind the scenes, and are quite close to having a new release with Spark 2.4.4. Stay tuned.

**Comment by andresdoncel-stratio** [comment]
Any updates on this issue? I'd like to know why was it closed.

**Comment by nicodv** [comment]
@andresdoncel-stratio , see comments in this PR for the latest info: https://github.com/salesforce/TransmogrifAI/pull/402

**Comment by nicodv** [comment]
For those interested: the Spark 2.4.4 upgrade has been merged to the master branch.

In the meantime, Spark 2.4.5 was released... We will be upgrading to that soon, and subsequently release a new TransmogrifAI 0.7.0 version based on that.
