### ISSUE TITLE
Redundant end-tag appeared at line#259 in pom.xml

### ISSUE THREAD

**Issue by rshiue** [salesforce/TransmogrifAI#451]
**Describe the bug**
Redundant end-tag(the ">" symbol) appeared in pom.xml.

**To Reproduce**
Please checkout the pom.xml at line#259. 
(SHA1: 3d51d5defcd1005bf255b12fac55003e1c942f11)

**Expected behavior**
There should be exactly one end tag.

**Logs or screenshots**
<img width="574" alt="2-close-tags" src="https://user-images.githubusercontent.com/812170/71400661-674d6f80-2662-11ea-95b5-0253cb3f01aa.png">

**Additional context**
None.

**Comment by tovbinm** [comment]
Thank you. FYI, Pom.xml is only used to security check project dependencies and not for actual builds. Please use gradle instead.
