### ISSUE TITLE
How to obtain the vertex of multi-classification roc graph

### ISSUE THREAD

**Issue by shenzgang** [salesforce/TransmogrifAI#454]
How to obtain the vertex of multi-classification roc graph？

**Comment by tovbinm** [comment]
TransmogrifAI exposes [MultiClassificationMetrics](https://github.com/salesforce/TransmogrifAI/blob/51037a80ee6ef48c5c905ee967187288d78559cb/core/src/main/scala/com/salesforce/op/evaluators/OpMultiClassificationEvaluator.scala#L260) computed by underlying [MulticlassClassificationEvaluator](https://spark.apache.org/docs/2.3.2/api/scala/index.html#org.apache.spark.ml.evaluation.MulticlassClassificationEvaluator) in Apache Spark. Particular vertices are not available.

You can implement a custom evaluator either by using a handy factory [Evaluators.MultiClassification.custom](https://github.com/salesforce/TransmogrifAI/blob/51037a80ee6ef48c5c905ee967187288d78559cb/core/src/main/scala/com/salesforce/op/evaluators/Evaluators.scala#L200) or by extending [OpMultiClassificationEvaluatorBase](https://github.com/salesforce/TransmogrifAI/blob/51037a80ee6ef48c5c905ee967187288d78559cb/core/src/main/scala/com/salesforce/op/evaluators/OpEvaluatorBase.scala#L213)
