### ISSUE TITLE
demo in java language

### ISSUE THREAD

**Issue by wangyu4882** [salesforce/TransmogrifAI#480]
Hi,  

I  want to use TransmogrifAI  in JAVA env, and  I found so hard to translate scala examples to java. 

Can anybody provide some demos for use TransmogrifAI  with java ?

**Comment by tovbinm** [comment]
Invoking TransmogrifAI from Java would be very difficult, due to various Scala only language features we rely on. For example TypeTags or Macros. I would not recommend to go into that direction and use it with Scala as designed.
