### ISSUE TITLE
Make AvroInOut#selectExistingPaths more robust and readable

### ISSUE THREAD

**Issue by gerashegalov** [salesforce/TransmogrifAI#483]
**Describe the bug**
The logic for instantiating the filesystem object is [unnecessarily complex](https://github.com/gerashegalov/TransmogrifAI/blob/04cd7ff35d2ecab46180cf9689a7a53148957319/utils/src/main/scala/com/salesforce/op/utils/io/avro/AvroInOut.scala#L90). `selectExistingPaths` relies on the side effect of Path creation to detect that no paths were passed to begin with but after actually creating the filesytem object on the empty path.

**Expected behavior**
Convert array of strings to array of Hadooo Path objects right away. This will already bail on the empty paths. Obtaining FS is just `val fs = firstFile.getFileSystem(sc.hadoopConfiguration)`. Then filter as is.

**Comment by sakhuja** [comment]
@gerashegalov I can take a look at this. Thanks,

**Comment by gerashegalov** [comment]
resolved by #486
