### ISSUE TITLE
Unable to import import com.salesforce.op._ on Spark Magic (Jupyter Notebook)

### ISSUE THREAD

**Issue by ahlag** [salesforce/TransmogrifAI#488]
I was trying to import the transmogrifyAI for use on Spark Magic with Spark. However, the object salesforce couldn't be identified as a member of package com. I built the packages with `./gradlew core:shadowJar`.

```
<console>:26: error: object salesforce is not a member of package com
       import com.salesforce.transmogrifai
```

**Comment by tovbinm** [comment]
We provided some instructions to use TransmogrifAI from Jupyter notebooks here - https://docs.transmogrif.ai/en/stable/examples/Running-from-Jupyter-Notebook.html

We recommend to install it from mvn as follows:

![image](https://user-images.githubusercontent.com/629845/86483215-6e87c100-bd08-11ea-94ab-4d8b1a9a59f1.png)

**Comment by ahlag** [comment]
Thank you! It worked.
