### ISSUE TITLE
Did the documentation site's domain name expire?

### ISSUE THREAD

**Issue by paulkass** [salesforce/TransmogrifAI#499]
It seems like the documentation site is down at [https://transmogrif.ai/](https://transmogrif.ai/). It refuses to connect with https and shows a NameCheap parking page when not using http.

Screenshots:
![image](https://user-images.githubusercontent.com/5911154/88619033-6b55cb80-d04f-11ea-9eff-2638e7755cb5.png)

**Comment by tovbinm** [comment]
Thank you for letting us know. We are aware of the issue. We will get the site back soon.

**Comment by tovbinm** [comment]
It should be back to normal now.
