### ISSUE TITLE
The effect of random seeds on results ?

### ISSUE THREAD

**Issue by shenzgang** [salesforce/TransmogrifAI#559]
When I use Titan tests I get different and very different estimates each time. Does random seeding have that much of an impact?

**Comment by tovbinm** [comment]
Yes, indeed. In order to get a predictable behavior you can set random seed in your tests. Depending on your tests structure where you set the seed might vary. For example - https://github.com/salesforce/TransmogrifAI/blob/master/helloworld/src/main/scala/com/salesforce/hw/titanic/OpTitanic.scala#L50,

**Comment by shenzgang** [comment]
Thanks for your reply!  There is also the question of how to use the generated model to predict unlabeled test sample data. Are there any examples of using model prediction?

**Comment by tovbinm** [comment]
You can [save a trained model](https://docs.transmogrif.ai/en/stable/developer-guide/index.html?highlight=save#saving-fitted-workflows), then [load it](https://docs.transmogrif.ai/en/stable/developer-guide/index.html?highlight=save#loading-saved-workflows) later, set [a new scoring reader](https://github.com/salesforce/TransmogrifAI/blob/master/core/src/main/scala/com/salesforce/op/OpWorkflowCore.scala#L123) / [a new input dataset](https://github.com/salesforce/TransmogrifAI/blob/master/core/src/main/scala/com/salesforce/op/OpWorkflowCore.scala#L147), and finally compute scores by invoking [`score()`](https://github.com/salesforce/TransmogrifAI/blob/master/core/src/main/scala/com/salesforce/op/OpWorkflowModel.scala#L261).

You can also use [transmogrifai-local](https://github.com/salesforce/TransmogrifAI/tree/master/local) for on-line serving of your model (e.g over HTTP API)

**Comment by shenzgang** [comment]
The data set used for model training is labeled column, while the test data is not labeled column. When calling score(), an exception will be thrown

**Comment by leahmcguire** [comment]
You will need to create an empty label column
