### ISSUE TITLE
Issue running on Databricks

### ISSUE THREAD

**Issue by mikeyoungyoung** [salesforce/TransmogrifAI#81]
I'm having issue accessing the spark context when running on databricks. I've imported all libraries as part of the examples in the titanic snippet but now luck

See screenshot
<img width="832" alt="screen shot 2018-08-23 at 2 29 36 pm" src="https://user-images.githubusercontent.com/2731660/44544797-39a88d00-a6e1-11e8-8b80-68d8007776f6.png">

**Comment by tovbinm** [comment]
In Databricks notebooks and Spark REPL, the SparkSession has been created automatically and assigned to variable spark. All needs to be done is to make sure that SparkSession is present implicitly:
```scala
implicit val ss = spark
```

**Comment by mikeyoungyoung** [comment]
@tovbinm cool, thanks for that tip work now (with ss replaced with sc though, I assume that was a typo)
