### ISSUE TITLE
Cannot find getRawFeatureDistribution() in any files

### ISSUE THREAD

**Issue by wdxtub** [salesforce/TransmogrifAI#85]
I've seen a definition about getRawFeatureDistribution() method in https://scaladoc.transmogrif.ai/index.html#package. But I can't find any related code in current commit. How can I get raw feature distribution for now?

**Comment by ajayborra** [comment]
Try steps from [this installation guide](https://docs.transmogrif.ai/en/stable/installation/index.html) to build the code from the master branch.

**Comment by tovbinm** [comment]
Scaladoc is generated from the latest (i.e master) branch.

**Comment by tovbinm** [comment]
We are going to publish 0.3.5 soon.

**Comment by tovbinm** [comment]
Release docs can be found here https://www.javadoc.io/doc/com.salesforce.transmogrifai/transmogrifai-core_2.11/0.3.4
