### ISSUE TITLE
Build & tests parallelism - Part I

### ISSUE THREAD

**Issue by tovbinm** [salesforce/TransmogrifAI#90]
**Problem**
Currently our build & tests are sequential, perhaps it would be better to have it parallelized.

**Solution**
- Parallelize build & tests using Gradle (if not possible, leverage CircleCI parallelism)
- Evaluate performance difference

**Alternatives**
N/A

**Comment by ajayborra** [comment]
@tovbinm Raised a PR with optimization to gradle. We could try further optimization on CircleCI as well.

**Comment by tovbinm** [comment]
thank you!
